language: go
go:
 - 1.2.2
 - 1.3
install:
 - mkdir ${HOME}/bin
 - export PATH=${PATH}:${HOME}/bin
 - export GOBIN=${HOME}/bin
 - go get code.google.com/p/go.tools/cmd/vet
 - go get -t -v ./...
 - go get golang.org/x/lint/golint
 - go install -a -race std

script:
 - golint .
 - go vet ./...
 - go build ./...
 - go test -race -v ./...
